/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */

plugins {
    id 'java-test-fixtures'
    id 'org.apache.grails.buildsrc.properties'
    id 'org.apache.grails.buildsrc.dependency-validator'
    id 'org.apache.grails.gradle.grails-plugin'
    id 'org.apache.grails.buildsrc.compile'
    id 'org.apache.grails.buildsrc.configuration-metadata'
    id 'org.apache.grails.buildsrc.publish'
    id 'org.apache.grails.buildsrc.sbom'
    id 'org.apache.grails.buildsrc.vulnerability-scan'
    id 'org.apache.grails.gradle.grails-code-style'
    id 'org.apache.grails.gradle.grails-jacoco'
}

version = projectVersion
group = 'org.apache.grails'

ext {
    pomDescription = 'Grails JSON Views'
}

dependencies {
    implementation platform(project(':grails-bom'))
    testFixturesImplementation platform(project(':grails-bom'))

    api project(':grails-views-core') // Used in public API
    api project(':grails-rest-transforms') // Used in public API

    implementation project(':grails-common'), {
        // impl: GrailsMessageSourceUtils
    }
    implementation project(':grails-encoder')
    implementation 'org.apache.groovy:groovy'
    implementation 'org.apache.groovy:groovy-json'
    implementation 'jakarta.validation:jakarta.validation-api'

    compileOnly 'org.slf4j:slf4j-nop' // Prevents warning about missing slf4j implementation during compilation

    testImplementation project(':grails-testing-support-views-gson')
    testImplementation project(':grails-testing-support-core')
    testImplementation project(':grails-testing-support-datamapping')
    testImplementation project(':grails-data-hibernate5-core')
    testImplementation 'jakarta.servlet:jakarta.servlet-api'
    testImplementation 'org.slf4j:slf4j-nop' // Prevents warning about missing slf4j implementation during compilation and tests
    testImplementation 'org.spockframework:spock-core'
    testImplementation 'tools.jackson.core:jackson-databind'

    testRuntimeOnly 'org.objenesis:objenesis' // Required by Spock for mocking classes without default constructor
}

def testArtifacts = ['*.gson', 'circular/**']

tasks.named('jar', Jar).configure {
    it.exclude testArtifacts
}
tasks.named('sourcesJar', Jar).configure {
    it.exclude testArtifacts
}

apply {
    from rootProject.layout.projectDirectory.file('gradle/docs-config.gradle')
    from rootProject.layout.projectDirectory.file('gradle/test-config.gradle')
    from rootProject.layout.projectDirectory.file('gradle/grails-extension-gradle-config.gradle')
}
