# See https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/exploring-the-dependencies-of-a-repository#changing-the-used-by-package
# This file associates this repository with packages published to external registries (Maven Central)
# so that GitHub can display the correct "Used by" package on the repository page.
# The Package URL (purl) format is defined at https://github.com/package-url/purl-spec

version: 1
references:
  - purl: pkg:maven/org.apache.grails/grails-async
  - purl: pkg:maven/org.apache.grails/grails-async-core
  - purl: pkg:maven/org.apache.grails/grails-async-gpars
  - purl: pkg:maven/org.apache.grails/grails-async-rxjava
  - purl: pkg:maven/org.apache.grails/grails-async-rxjava2
  - purl: pkg:maven/org.apache.grails/grails-async-rxjava3
  - purl: pkg:maven/org.apache.grails/grails-bom
  - purl: pkg:maven/org.apache.grails/grails-bootstrap
  - purl: pkg:maven/org.apache.grails/grails-cache
  - purl: pkg:maven/org.apache.grails/grails-codecs
  - purl: pkg:maven/org.apache.grails/grails-codecs-core
  - purl: pkg:maven/org.apache.grails/grails-common
  - purl: pkg:maven/org.apache.grails/grails-console
  - purl: pkg:maven/org.apache.grails/grails-controllers
  - purl: pkg:maven/org.apache.grails/grails-converters
  - purl: pkg:maven/org.apache.grails/grails-core
  - purl: pkg:maven/org.apache.grails/grails-databinding
  - purl: pkg:maven/org.apache.grails/grails-datamapping-async
  - purl: pkg:maven/org.apache.grails/grails-datasource
  - purl: pkg:maven/org.apache.grails/grails-dependencies-assets
  - purl: pkg:maven/org.apache.grails/grails-dependencies-starter-web
  - purl: pkg:maven/org.apache.grails/grails-dependencies-test
  - purl: pkg:maven/org.apache.grails/grails-domain-class
  - purl: pkg:maven/org.apache.grails/grails-events
  - purl: pkg:maven/org.apache.grails/grails-events-compat
  - purl: pkg:maven/org.apache.grails/grails-events-rxjava
  - purl: pkg:maven/org.apache.grails/grails-events-rxjava2
  - purl: pkg:maven/org.apache.grails/grails-events-rxjava3
  - purl: pkg:maven/org.apache.grails/grails-geb
  - purl: pkg:maven/org.apache.grails/grails-gsp
  - purl: pkg:maven/org.apache.grails/grails-interceptors
  - purl: pkg:maven/org.apache.grails/grails-layout
  - purl: pkg:maven/org.apache.grails/grails-logging
  - purl: pkg:maven/org.apache.grails/grails-micronaut
  - purl: pkg:maven/org.apache.grails/grails-mimetypes
  - purl: pkg:maven/org.apache.grails/grails-profiles-base
  - purl: pkg:maven/org.apache.grails/grails-profiles-plugin
  - purl: pkg:maven/org.apache.grails/grails-profiles-profile
  - purl: pkg:maven/org.apache.grails/grails-profiles-rest-api
  - purl: pkg:maven/org.apache.grails/grails-profiles-rest-api-plugin
  - purl: pkg:maven/org.apache.grails/grails-profiles-web
  - purl: pkg:maven/org.apache.grails/grails-profiles-web-plugin
  - purl: pkg:maven/org.apache.grails/grails-rest-transforms
  - purl: pkg:maven/org.apache.grails/grails-scaffolding
  - purl: pkg:maven/org.apache.grails/grails-services
  - purl: pkg:maven/org.apache.grails/grails-shell-cli
  - purl: pkg:maven/org.apache.grails/grails-sitemesh3
  - purl: pkg:maven/org.apache.grails/grails-spring
  - purl: pkg:maven/org.apache.grails/grails-taglib
  - purl: pkg:maven/org.apache.grails/grails-test-core
  - purl: pkg:maven/org.apache.grails/grails-testing-support-core
  - purl: pkg:maven/org.apache.grails/grails-testing-support-datamapping
  - purl: pkg:maven/org.apache.grails/grails-testing-support-mongodb
  - purl: pkg:maven/org.apache.grails/grails-testing-support-views-gson
  - purl: pkg:maven/org.apache.grails/grails-testing-support-web
  - purl: pkg:maven/org.apache.grails/grails-url-mappings
  - purl: pkg:maven/org.apache.grails/grails-validation
  - purl: pkg:maven/org.apache.grails/grails-web-boot
  - purl: pkg:maven/org.apache.grails/grails-web-gsp
  - purl: pkg:maven/org.apache.grails/grails-web-gsp-taglib
  - purl: pkg:maven/org.apache.grails/grails-web-jsp
  - purl: pkg:maven/org.apache.grails/grails-web-mvc
  - purl: pkg:maven/org.apache.grails/grails-web-taglib
  - purl: pkg:maven/org.apache.grails/grails-web-url-mappings
  - purl: pkg:maven/org.apache.grails/grails-wrapper
  - purl: pkg:maven/org.apache.grails.data/grails-data-hibernate5
  - purl: pkg:maven/org.apache.grails.data/grails-data-hibernate5-core
  - purl: pkg:maven/org.apache.grails.data/grails-data-hibernate5-dbmigration
  - purl: pkg:maven/org.apache.grails.data/grails-data-hibernate5-spring-boot
  - purl: pkg:maven/org.apache.grails.data/grails-data-mongodb
  - purl: pkg:maven/org.apache.grails.data/grails-data-mongodb-bson
  - purl: pkg:maven/org.apache.grails.data/grails-data-mongodb-core
  - purl: pkg:maven/org.apache.grails.data/grails-data-mongodb-ext
  - purl: pkg:maven/org.apache.grails.data/grails-data-mongodb-gson-templates
  - purl: pkg:maven/org.apache.grails.data/grails-data-mongodb-spring-boot
  - purl: pkg:maven/org.apache.grails.data/grails-data-simple
  - purl: pkg:maven/org.apache.grails.data/grails-datamapping-core
  - purl: pkg:maven/org.apache.grails.data/grails-datamapping-core-test
  - purl: pkg:maven/org.apache.grails.data/grails-datamapping-support
  - purl: pkg:maven/org.apache.grails.data/grails-datamapping-tck
  - purl: pkg:maven/org.apache.grails.data/grails-datamapping-tck-base
  - purl: pkg:maven/org.apache.grails.data/grails-datamapping-tck-domains
  - purl: pkg:maven/org.apache.grails.data/grails-datamapping-tck-tests
  - purl: pkg:maven/org.apache.grails.data/grails-datamapping-validation
  - purl: pkg:maven/org.apache.grails.data/grails-datastore-async
  - purl: pkg:maven/org.apache.grails.data/grails-datastore-core
  - purl: pkg:maven/org.apache.grails.data/grails-datastore-web
  - purl: pkg:maven/org.apache.grails.databinding/grails-databinding-core
  - purl: pkg:maven/org.apache.grails.events/grails-events-core
  - purl: pkg:maven/org.apache.grails.events/grails-events-gpars
  - purl: pkg:maven/org.apache.grails.events/grails-events-spring
  - purl: pkg:maven/org.apache.grails.events/grails-events-transforms
  - purl: pkg:maven/org.apache.grails.i18n/grails-i18n
  - purl: pkg:maven/org.apache.grails.views/grails-gsp-core
  - purl: pkg:maven/org.apache.grails.views/grails-views-core
  - purl: pkg:maven/org.apache.grails.views/grails-views-gson
  - purl: pkg:maven/org.apache.grails.views/grails-views-markup
  - purl: pkg:maven/org.apache.grails.web/grails-encoder
  - purl: pkg:maven/org.apache.grails.web/grails-web-common
  - purl: pkg:maven/org.apache.grails.web/grails-web-core
  - purl: pkg:maven/org.apache.grails.web/grails-web-databinding
  - purl: pkg:maven/org.apache.grails.web/grails-web-gsp
  - purl: pkg:maven/org.apache.grails.web/grails-web-gsp-taglib
  - purl: pkg:maven/org.apache.grails.web/grails-web-jsp
  - purl: pkg:maven/org.apache.grails.web/grails-web-mvc
  - purl: pkg:maven/org.apache.grails.web/grails-web-taglib
  - purl: pkg:maven/org.apache.grails.web/grails-web-url-mappings

  # Legacy Maven coordinates (pre-Apache rename). See RENAME.md for mapping
  - purl: pkg:maven/org.grails.plugins/async
  - purl: pkg:maven/org.grails/grails-async
  - purl: pkg:maven/org.grails/grails-async-gpars
  - purl: pkg:maven/org.grails/grails-async-rxjava
  - purl: pkg:maven/org.grails/grails-async-rxjava2
  - purl: pkg:maven/org.grails/grails-async-rxjava3
  - purl: pkg:maven/org.grails/grails-bom
  - purl: pkg:maven/org.grails/grails-bootstrap
  - purl: pkg:maven/org.grails.plugins/cache
  - purl: pkg:maven/org.grails/grails-plugin-codecs
  - purl: pkg:maven/org.grails/grails-codecs
  - purl: pkg:maven/org.grails/grails-console
  - purl: pkg:maven/org.grails/grails-plugin-controllers
  - purl: pkg:maven/org.grails.plugins/converters
  - purl: pkg:maven/org.grails/grails-core
  - purl: pkg:maven/org.grails/grails-plugin-databinding
  - purl: pkg:maven/org.grails/grails-databinding
  - purl: pkg:maven/org.grails/grails-plugin-datasource
  - purl: pkg:maven/org.grails/grails-dependencies
  - purl: pkg:maven/org.grails/grails-plugin-domain-class
  - purl: pkg:maven/org.grails/grails-encoder
  - purl: pkg:maven/org.grails.plugins/events
  - purl: pkg:maven/org.grails/grails-events
  - purl: pkg:maven/org.grails/grails-events-compat
  - purl: pkg:maven/org.grails/grails-events-gpars
  - purl: pkg:maven/org.grails/grails-events-rxjava
  - purl: pkg:maven/org.grails/grails-events-rxjava2
  - purl: pkg:maven/org.grails/grails-events-rxjava3
  - purl: pkg:maven/org.grails/grails-events-spring
  - purl: pkg:maven/org.grails/grails-events-transform
  - purl: pkg:maven/org.grails.plugins/geb
  - purl: pkg:maven/org.grails.plugins/gsp
  - purl: pkg:maven/org.grails/grails-gsp
  - purl: pkg:maven/org.grails/grails-logging
  - purl: pkg:maven/org.grails/grails-plugin-i18n
  - purl: pkg:maven/org.grails/grails-plugin-interceptors
  - purl: pkg:maven/org.grails/grails-plugin-mimetypes
  - purl: pkg:maven/org.grails/grails-plugin-rest
  - purl: pkg:maven/org.grails.plugins/scaffolding
  - purl: pkg:maven/org.grails/grails-plugin-services
  - purl: pkg:maven/org.grails/grails-shell
  - purl: pkg:maven/org.grails/grails-spring
  - purl: pkg:maven/org.grails/grails-taglib
  - purl: pkg:maven/org.grails/grails-test
  - purl: pkg:maven/org.grails/grails-testing-support
  - purl: pkg:maven/org.grails/grails-plugin-url-mappings
  - purl: pkg:maven/org.grails/grails-plugin-validation
  - purl: pkg:maven/org.grails/views-core
  - purl: pkg:maven/org.grails.plugins/views-json
  - purl: pkg:maven/org.grails/views-json-testing-support
  - purl: pkg:maven/org.grails/views-markup
  - purl: pkg:maven/org.grails/grails-web
  - purl: pkg:maven/org.grails/grails-web-boot
  - purl: pkg:maven/org.grails/grails-web-common
  - purl: pkg:maven/org.grails/grails-web-databinding
  - purl: pkg:maven/org.grails/grails-web-gsp
  - purl: pkg:maven/org.grails/grails-web-gsp-taglib
  - purl: pkg:maven/org.grails/grails-web-jsp
  - purl: pkg:maven/org.grails/grails-web-mvc
  - purl: pkg:maven/org.grails/grails-web-taglib
  - purl: pkg:maven/org.grails/grails-web-testing-support
  - purl: pkg:maven/org.grails/grails-web-url-mappings
  - purl: pkg:maven/org.grails/grails-datastore-gorm-async
  - purl: pkg:maven/org.grails/grails-datastore-gorm
  - purl: pkg:maven/org.grails/grails-datastore-gorm-test
  - purl: pkg:maven/org.grails/grails-datastore-gorm-hibernate5
  - purl: pkg:maven/org.grails/grails-datastore-gorm-mongodb
  - purl: pkg:maven/org.grails/grails-datastore-gorm-mongodb-ext
  - purl: pkg:maven/org.grails/grails-datastore-gorm-mongodb-bson
  - purl: pkg:maven/org.grails/grails-datastore-gorm-support
  - purl: pkg:maven/org.grails/grails-gorm-testing-support
  - purl: pkg:maven/org.grails/grails-datastore-gorm-validation
  - purl: pkg:maven/org.grails.plugins/mongodb
  - purl: pkg:maven/org.grails.plugins/views-json-templates
  - purl: pkg:maven/org.grails/gorm-mongodb-spring-boot
  - purl: pkg:maven/org.grails/grails-datastore-gorm-simple
  - purl: pkg:maven/org.grails/grails-datastore-async
  - purl: pkg:maven/org.grails/grails-datastore-core
  - purl: pkg:maven/org.grails/grails-datastore-web
  - purl: pkg:maven/org.grails.profiles/base
  - purl: pkg:maven/org.grails.profiles/plugin
  - purl: pkg:maven/org.grails.profiles/profile
  - purl: pkg:maven/org.grails.profiles/rest-api
  - purl: pkg:maven/org.grails.profiles/rest-api-plugin
  - purl: pkg:maven/org.grails.profiles/web
  - purl: pkg:maven/org.grails.profiles/web-plugin