/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */

dependencies {
    // https://docs.gradle.org/8.3/userguide/upgrading_version_8.html#test_framework_implementation_dependencies
    add('testRuntimeOnly', 'org.junit.platform:junit-platform-launcher')
}

tasks.withType(Test).configureEach {
    onlyIf {
        ![
                'skipSpringSecurityTests',
                'onlyFunctionalTests',
                'onlyHibernate5Tests',
                'onlyHibernate7Tests',
                'onlyMongodbTests',
                'onlyRedisTests',
                'onlyCoreTests',
                'skipTests'
        ].find {
            project.hasProperty(it)
        }
    }

    useJUnitPlatform()
    testLogging {
        exceptionFormat = 'full'
        events 'passed', 'skipped', 'failed'//, 'standardOut', 'standardError'
    }
    addTestListener([
            beforeTest: { descriptor -> logger.quiet(" -- $descriptor") }
    ] as TestListener)
}

pluginManager.withPlugin('org.apache.grails.gradle.grails-integration-test') {
    tasks.named('integrationTest', Test) {
        systemProperty('geb.build.reportsDir', reporting.file("$projectDir/build/geb-reports"))
        systemProperty('grails.geb.reporting.directory', reporting.file("$projectDir/build/geb-reports").canonicalFile.absolutePath)
        // systemProperty('grails.geb.recording.mode', 'RECORD_ALL')
        systemProperty('TESTCONFIG', System.getProperty('TESTCONFIG'))

        // Waiting at-checks keep Geb tests resilient when a page is still loading after navigation.
        systemProperty('grails.geb.atCheckWaiting.enabled', 'true')
        systemProperty('grails.geb.timeouts.timeout', '30')

        doFirst {
            logger.quiet(
                    '\n - Running tests for configuration: {}',
                    System.getProperty('TESTCONFIG', 'N/S')
            )
        }
    }
}
