/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */

plugins {
    id 'groovy'
    id 'java-library'
    id 'org.apache.grails.buildsrc.properties'
    id 'org.apache.grails.buildsrc.dependency-validator'
    id 'org.apache.grails.buildsrc.compile'
    id 'org.apache.grails.buildsrc.publish'
    id 'org.apache.grails.buildsrc.sbom'
    id 'org.apache.grails.buildsrc.vulnerability-scan'
    id 'org.apache.grails.gradle.grails-code-style'
    id 'org.apache.grails.gradle.grails-jacoco'
}

version = projectVersion
group = 'org.apache.grails'

ext {
    pomTitle = 'Grails GORM'
    pomDescription = 'GORM - Grails Data Access Framework'
}

dependencies {

    implementation platform(project(':grails-bom'))

    api project(':grails-datamapping-core'), {
        // api: GormEntity, GormStaticApi, GormOperations, GormStaticOperations
        // impl: GormEnhancer
        if (excludeUnusedTransDeps) {
            // API dependencies in grails-datamapping-core
            exclude group: 'jakarta.annotation', module: 'jakarta.annotation-api'
            //exclude group: 'jakarta.persistence', module: 'jakarta.persistence-api' // Entity
            //exclude group: 'org.apache.grails.data', module: 'grails-datastore-core' // DirtyCheckable
            exclude group: 'org.apache.grails.data', module: 'grails-datamapping-validation'
            //exclude group: 'org.springframework', module: 'spring-context' // Errors
            exclude group: 'org.springframework', module: 'spring-jdbc'
            //exclude group: 'org.springframework', module: 'spring-tx' // TransactionDefinition
        }
    }
    api project(':grails-async-core'), {
        // api: Promise, PromiseDecorator, PromiseDecoratorProvider
        // impl: Promises
    }

    compileOnlyApi project(':grails-datastore-async'), {
        // AST (source retention annotation): DelegateAsync
        if (excludeUnusedTransDeps) {
            // API dependencies in grails-datastore-async
            exclude group: 'org.apache.grails.async', module: 'grails-async'
        }
    }

    compileOnly 'org.apache.groovy:groovy'
}

apply {
    from rootProject.layout.projectDirectory.file('gradle/test-config.gradle')
    from rootProject.layout.projectDirectory.file('gradle/docs-config.gradle')
}
