contact_links:
  - name: Grails Core Discussions
    url: https://github.com/grails/grails-core/discussions
    about: Ask questions about Grails® framework on Github
  - name: Stack Overflow
    url: https://stackoverflow.com/tags/grails
    about: Ask questions on Stack Overflow
  - name: Grails Slack
    url: https://grails.slack.com/
    about: Chat with us on Grails Community Slack.