/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */

plugins {
    id 'groovy'
    id 'java-library'
    id 'project-report'
    id 'org.apache.grails.buildsrc.properties'
    id 'org.apache.grails.buildsrc.dependency-validator'
    id 'org.apache.grails.buildsrc.compile'
    id 'org.apache.grails.buildsrc.publish'
    id 'org.apache.grails.buildsrc.sbom'
    id 'org.apache.grails.gradle.grails-code-style'
    id 'org.apache.grails.gradle.grails-jacoco'
}

version = projectVersion
group = 'org.apache.grails.gradle'

ext {
    pomTitle = 'Grails Gradle Model'
    pomDescription = 'Classes to support the Grails Gradle Plugins'
    sbomProjectType = org.cyclonedx.model.Component.Type.LIBRARY.name()
}

dependencies {
    implementation platform(project(':grails-gradle-bom'))

    implementation project(':grails-gradle-common') // XmlParserFeature

    // compile grails-gradle-model with the Groovy version provided by Gradle
    // Groovy 4+ uses org.apache.groovy coordinates
    // when used by grails-gradle-plugin
    // see: https://docs.gradle.org/current/userguide/compatibility.html#groovy
    compileOnly 'org.apache.groovy:groovy'
    compileOnly 'org.apache.groovy:groovy-xml'

    testImplementation 'org.apache.groovy:groovy-test-junit5'
    testImplementation 'org.junit.jupiter:junit-jupiter-api'
    testImplementation 'org.junit.platform:junit-platform-suite'

    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'

    implementation 'org.springframework:spring-context'
    implementation 'org.springframework.boot:spring-boot-autoconfigure', {
        // impl: org.springframework.boot.env.YamlPropertySourceLoader
    }

    compileOnly 'org.jline:jline' // for profile compilation

    api 'org.yaml:snakeyaml'

    // Logging
    api 'org.slf4j:slf4j-api'
    api 'org.slf4j:jcl-over-slf4j'

    // Testing
    testImplementation 'org.apache.groovy:groovy'
    testImplementation 'org.apache.groovy:groovy-xml'
    testImplementation 'org.slf4j:slf4j-simple'
    testImplementation 'org.spockframework:spock-core'
}

apply {
    from rootProject.layout.projectDirectory.file('gradle/docs-config.gradle')
    from rootProject.layout.projectDirectory.file('gradle/test-config.gradle')
}