/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */
package grails.openapi

import io.swagger.v3.oas.models.OpenAPI
import io.swagger.v3.oas.models.PathItem

import grails.core.DefaultGrailsApplication
import grails.core.GrailsApplication
import grails.web.mapping.UrlMappingsHolder
import org.grails.support.MockApplicationContext
import org.grails.web.mapping.DefaultUrlMappingEvaluator
import org.grails.web.mapping.DefaultUrlMappingsHolder
import org.grails.web.util.WebUtils

import spock.lang.Specification

class UrlMappingsOpenApiCustomizerSpec extends Specification {

    void setup() {
        WebUtils.clearGrailsWebRequest()
    }

    void 'documents a statically mapped controller action'() {
        given:
        def openApi = new OpenAPI()
        def customizer = new UrlMappingsOpenApiCustomizer(holderFor {
            '/books'(controller: 'book', action: 'index', method: 'GET')
        })

        when:
        customizer.customise(openApi)

        then:
        with(openApi.paths['/books']) {
            get.tags == ['book']
            get.operationId == 'book_index_get'
            get.responses['200'].content.containsKey('application/json')
        }
    }

    void 'converts captured wildcards to named OpenAPI path parameters'() {
        given:
        def openApi = new OpenAPI()
        def customizer = new UrlMappingsOpenApiCustomizer(holderFor {
            "/books/$id"(controller: 'book', action: 'show', method: 'GET')
        })

        when:
        customizer.customise(openApi)

        then:
        openApi.paths.containsKey('/books/{id}')

        and:
        with(openApi.paths['/books/{id}'].get.parameters.first()) {
            name == 'id'
            it.in == 'path'
            required
        }
    }

    void 'documents every HTTP method generated by a resources mapping'() {
        given:
        def openApi = new OpenAPI()
        def customizer = new UrlMappingsOpenApiCustomizer(holderFor {
            '/books'(resources: 'book')
        })

        when:
        customizer.customise(openApi)

        then: 'the collection path supports listing and creation'
        openApi.paths['/books'].get
        openApi.paths['/books'].post

        and: 'the instance path supports the full lifecycle'
        with(openApi.paths['/books/{id}']) {
            get
            put
            delete
        }
    }

    void 'excludes the Grails response format suffix from the documented path'() {
        given:
        def openApi = new OpenAPI()
        def customizer = new UrlMappingsOpenApiCustomizer(holderFor {
            '/books'(resources: 'book')
        })

        when:
        customizer.customise(openApi)

        then: 'the optional .format extension is not part of any path'
        openApi.paths.keySet().every { !it.contains('(') && !it.contains('format') }

        and: 'format is not documented as a path parameter'
        openApi.paths['/books/{id}'].get.parameters*.name == ['id']
    }

    void 'skips mappings whose controller is only known per request'() {
        given:
        def openApi = new OpenAPI()
        def customizer = new UrlMappingsOpenApiCustomizer(holderFor {
            '/$controller/$action?/$id?'()
        })

        when:
        customizer.customise(openApi)

        then:
        openApi.paths == null || openApi.paths.isEmpty()
    }

    void 'documents an unrestricted mapping as GET'() {
        given:
        def openApi = new OpenAPI()
        def customizer = new UrlMappingsOpenApiCustomizer(holderFor {
            '/health'(controller: 'health', action: 'check')
        })

        when:
        customizer.customise(openApi)

        then:
        openApi.paths['/health'].readOperationsMap().keySet() == [PathItem.HttpMethod.GET] as Set
    }

    void 'preserves paths contributed by other springdoc customizers'() {
        given:
        def openApi = new OpenAPI()
        def customizer = new UrlMappingsOpenApiCustomizer(holderFor {
            '/books'(controller: 'book', action: 'index', method: 'GET')
        })
        customizer.customise(openApi)
        def existing = openApi.paths.size()

        when: 'a second customizer pass runs over the same document'
        customizer.customise(openApi)

        then: 'the document is unchanged rather than duplicated'
        openApi.paths.size() == existing
    }

    void 'skips a mapping declared for a method OpenAPI has no operation for'() {
        given:
        def openApi = new OpenAPI()
        def customizer = new UrlMappingsOpenApiCustomizer(holderFor {
            '/books'(controller: 'book', action: 'index', method: 'GET')
            '/books/report'(controller: 'book', action: 'report', method: 'REPORT')
        })

        when:
        customizer.customise(openApi)

        then: 'the unsupported mapping does not take the document down with it'
        openApi.paths['/books'].get

        and:
        !openApi.paths.containsKey('/books/report')
    }

    void 'names a greedy parameter for the constraint that binds it'() {
        given:
        def openApi = new OpenAPI()
        def customizer = new UrlMappingsOpenApiCustomizer(holderFor {
            "/files/$dir**"(controller: 'file', action: 'serve', method: 'GET')
        })

        when:
        customizer.customise(openApi)

        then: 'the template variable and the declared parameter agree'
        openApi.paths.containsKey('/files/{dir}')
        openApi.paths['/files/{dir}'].get.parameters*.name == ['dir']
    }

    void 'does not describe a response code mapping as a path'() {
        given:
        def openApi = new OpenAPI()
        def customizer = new UrlMappingsOpenApiCustomizer(holderFor {
            '/books'(controller: 'book', action: 'index', method: 'GET')
            '404'(controller: 'errors', action: 'notFound')
            '500'(view: '/error')
        })

        when:
        customizer.customise(openApi)

        then: 'a status code is not a URL'
        !openApi.paths.containsKey('/404')
        !openApi.paths.containsKey('/500')

        and:
        openApi.paths['/books'].get
    }

    void 'describes an optional token without leaving the optional marker in the path'() {
        given:
        def openApi = new OpenAPI()
        def customizer = new UrlMappingsOpenApiCustomizer(holderFor {
            "/books/$id?"(controller: 'book', action: 'show', method: 'GET')
        })

        when:
        customizer.customise(openApi)

        then: 'a question mark begins a query string, so it cannot appear in a path template'
        openApi.paths.keySet().every { !it.contains('?') }
        openApi.paths.containsKey('/books/{id}')
    }

    private static UrlMappingsHolder holderFor(Closure mappings) {
        def ctx = new MockApplicationContext()
        ctx.registerMockBean(GrailsApplication.APPLICATION_ID, new DefaultGrailsApplication())
        def evaluator = new DefaultUrlMappingEvaluator(ctx)
        new DefaultUrlMappingsHolder(evaluator.evaluateMappings(mappings))
    }
}
