# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

introduction:
  title: Introduction
  whatsNew:
    title: What's new in Grails {grailsMajorVersion}?
    dependencyUpgrades: Updated Dependencies
gettingStarted:
  title: Getting Started
  requirements: Installation Requirements
  downloadingAndInstalling: Downloading and Installing
  creatingAnApplication: Creating an Application
  aHelloWorldExample: Creating a Simple Web Application with Grails
  usingInteractiveMode: Using Interactive Mode
  ide: Getting Set Up in an IDE
  conventionOverConfiguration: Grails Directory Structure and Convention over Configuration
  runningAndDebuggingAnApplication: Running and Debugging an Application
  testingAnApplication: Testing an Application
  deployingAnApplication: Deploying an Application
  supportedJakartaEEContainers: Supported Jakarta EE Containers
  creatingArtefacts: Creating Artefacts
  generatingAnApplication: Generating an Application
  developmentReloading: Development Reloading
upgrading:
  title: Upgrading from the previous versions
  upgrading80x: Upgrading from Grails 7 to Grails 8
  upgrading72x: Upgrading from Grails 7.1 to Grails 7.2
  upgrading71x: Upgrading from Grails 7.0 to Grails 7.1
  upgrading70x: Upgrading from Grails 6 to Grails 7.0
  upgrading60x: Upgrading from Grails 5 to Grails 6
  upgrading50x: Upgrading from Grails 4 to Grails 5
  upgrading40x: Upgrading from Grails 3.3.x to Grails 4
conf:
  title: Configuration
  config:
    title: Configuration Types
    ymlPropertyOptions: YML Configuration
    externalConfiguration: External Configuration
    builtInOptions: Built-in Properties
    logging:
        title: Logging
        loggerName: Logger Names
        maskingRequestParametersFromStacktraceLogs: Masking Request Parameters From Stacktrace Logs
        loggingFullStackTraces: Logging Full Stack Traces
        externalLoggingConfiguration: External Configuration File
    configGORM: GORM
    proxyConfig: Configuring an HTTP proxy
  applicationClass:
      title: The Application Class
      executing: Executing the Application Class
      customizing: Customizing the Application Class
      applicationLifeCycle: The Application LifeCycle
  environments: Environments
  dataSource:
    title: The DataSource
    dataSourcesAndEnvironments: DataSources and Environments
    automaticDatabaseMigration: Automatic Database Migration
    transactionAwareDataSourceProxy: Transaction-aware DataSource Proxy
    databaseConsole: Database Console
    multipleDatasources: Multiple Datasources
  versioning: Versioning
  dependencyResolution: Dependency Resolution
commandLine:
  title: The Command Line
  interactiveMode: Interactive Mode
  creatingCustomScripts: Creating Custom Scripts
  creatingCustomCommands: Creating Custom Commands
  creatingProject: Creating a Grails Project
  reusingGrailsScripts: Re-using Grails scripts
  gradleBuild:
    title: Building with Gradle
    gradleDependencies: Defining Dependencies with Gradle
    gradleTasks: Working with Gradle Tasks
    gradlePlugins: Grails plugins for Gradle
profiles:
  title: Application Profiles
  standardProfiles:
    title: Standard Profiles
    webProfile: Web Profile
    restAPIProfile: REST API Profile
    pluginProfile: Plugin Profile
    webPluginProfile: Web Plugin Profile
    restAPIPluginProfile: REST API Plugin Profile
    profileProfile: Profile Profile
  creatingProfiles: Creating Profiles
  profileInheritance: Profile Inheritance
  publishingProfiles: Publishing Profiles
  profileStructure: Understanding Profiles
  profileCommands: Creating Profile Commands
  profileFeatures: Creating Profile Features
GORM:
  title: Object Relational Mapping (GORM)
  quickStartGuide:
    title: Quick Start Guide
    basicCRUD: Basic CRUD
  multiTenancy: Multi-Tenancy
  furtherReading: Further Reading on GORM
    
theWebLayer:
  title: The Web Layer
  controllers:
    title: Controllers
    understandingControllersAndActions: Understanding Controllers and Actions
    controllersAndScopes: Controllers and Scopes
    modelsAndViews: Models and Views
    redirectsAndChaining: Redirects and Chaining
    dataBinding: Data Binding
    jsonResponses: Responding with JSON
    moreOnJSONBuilder: More on JSONBuilder
    xmlResponses: Responding with XML    
    uploadingFiles: Uploading Files
    commandObjects: Command Objects
    formtokens: Handling Duplicate Form Submissions
    typeConverters: Simple Type Converters
    controllerExceptionHandling: Declarative Controller Exception Handling
  gsp:
    title: Groovy Server Pages
    GSPBasics:
      title: GSP Basics
      variablesAndScopes: Variables and Scopes
      logicAndIteration: Logic and Iteration
      pageDirectives: Page Directives
      expressions: Expressions
    tags:
      title: GSP Tags
      tagVariablesAndScopes: Variables and Scopes
      tagLogicAndIteration: Logic and Iteration
      searchAndFiltering: Search and Filtering
      linksAndResources: Links and Resources
      formsAndFields: Forms and Fields
      tagsAsMethodCalls: Tags as Method Calls
    viewsAndTemplates: Views and Templates
    gspStaticCompilation: Static Compilation
    layouts:
      title: Layouts
      contentBlocks: Content Blocks
    resources: Static Resources
    makingChangesToADeployedApplication: Making Changes to a Deployed Application
    taglibs:
      title: Tag Libraries
      taglibVariablesAndScopes: Variables and Scopes
      simpleTags: Simple Tags
      logicalTags: Logical Tags
      iterativeTags: Iterative Tags
      namespaces: Tag Namespaces
      compiledTags: Compiled Tag Resolution
      usingJSPTagLibraries: Using JSP Tag Libraries
      tagReturnValue: Tag return value
  fields:
    title: Fields Plugin
    fieldsInstallation: Installation
    fieldsUsage: Usage
    customizingFieldRendering: Customizing Field Rendering
    fieldsEmbeddedProperties: Embedded Properties
    fieldsThemes: Themes
    includingTemplatesInPlugins: Including Templates in Plugins
    fieldsPerformance: Performance
    fieldsScaffolding: Scaffolding
  gson:
    title: JSON Views
    jsonInstallation: Installation
    gsonTemplates: Templates
    gsonRendering: Rendering Domain Classes
    jsonViewApi: JSON View API
    gsonModelNaming: Model Naming
    gsonContentNegotiation: Content Negotiation
    gsonHal: HAL Support
    jsonapi: JSON API Support
    templateEngine: The JsonTemplateEngine
    staticCompilation: Static Compilation
    gsonTesting: Testing
    pluginSupport: Plugin Support
    jsonConfiguration: Configuration
    converters: Custom Converters
    gsonIntellij: IntelliJ Support
    gsonDebugging: Debugging Views
  markup:
    title: Markup Views
    markupInstallation: Installation
    markupViewApi: Markup View API
    markupConfiguration: Configuration
  urlmappings:
    title: URL Mappings
    mappingToControllersAndActions: Mapping to Controllers and Actions
    restfulMappings: Mapping to REST resources
    redirectMappings: Redirects In URL Mappings
    embeddedVariables: Embedded Variables
    mappingToViews: Mapping to Views
    mappingToResponseCodes: Mapping to Response Codes
    mappingHTTP: Mapping to HTTP methods
    mappingWildcards: Mapping Wildcards
    automaticLinkRewriting: Automatic Link Re-Writing
    applyingConstraints: Applying Constraints
    namedMappings: Named URL Mappings
    customizingUrlFormat: Customizing URL Formats
    namespacedControllers: Namespaced Controllers
  cors: CORS
  interceptors:
    title: Interceptors
    definingInterceptors: Defining Interceptors
    interceptorMatching: Matching Requests with Interceptors
    interceptorOrdering: Ordering Interceptor Execution
  contentNegotiation: Content Negotiation
traits:
  title: Traits
  traitsprovided:
    title: Traits Provided by Grails
    example:
        title: WebAttributes Trait Example
REST:
  title: REST
  domainResources: Domain classes as REST resources
  restUrlMappings: Mapping to REST resources
  linkingToResources: Linking to REST resources from GSP pages
  versioningResources: Versioning REST resources
  restfulControllers:
    title: Implementing REST controllers
    extendingRestfulController: Extending the RestfulController super class
    restControllersStepByStep: Implementing REST Controllers Step by Step
    generatingRestControllers: Generating a REST controller using scaffolding
  callingRestServices: Calling REST Services with HttpClient
  restProfile: The REST Profile
  openApi: OpenAPI and Swagger UI
  jsonViews:
    title: JSON Views
    jsonViewsSetup: Getting Started
    jsonViewsCreating: Creating JSON Views 
    jsonViewsAndTemplates: JSON View Templates
    jsonViewsAndDomainClasses: Rendering Domain Classes with JSON Views
    jsonViewsTemplatesAndConventions: JSON Views by Convention
  renderers:
    title: Customizing Response Rendering
    defaultRenderers: Customizing the Default Renderers
    customRenderers: Implementing a Custom Renderer
    gspRenderers: Using GSP to Customize Rendering
  hypermedia:
    title: Hypermedia as the Engine of Application State
    hal: HAL Support
    atom: Atom Support
    vndError: Vnd.Error Support
  binding: Customizing Binding of Resources
  RSSAndAtom: RSS and Atom
async:
  title: Asynchronous Programming
  asyncPromises: Promises
  events:
    title: Events
    asyncNotifying: Event Publishing
    asyncConsuming: Subscribing to Events
    asyncAnnotations: Reactor Spring Annotations
    asyncGormEvents: Events from GORM
    asyncSpringEvents: Events from Spring
    asyncConfigure: Configure the Default Event Bus
  asyncGorm: Asynchronous GORM
  rxjava:
    title: RxJava Support
    asyncServerSentEvents: Server Sent Events
    asyncRxGorm: RxGORM
  asyncRequests: Asynchronous Request Handling
  asyncServletApi: Servlet 3.0 Async
validation:
  title: Validation
  constraints: Declaring Constraints
  validatingConstraints: Validating Constraints
  sharingConstraints: Sharing Constraints Between Classes
  validationOnTheClient: Validation on the Client
  validationAndInternationalization: Validation and Internationalization
  validationNonDomainAndCommandObjectClasses: Applying Validation to Other Classes
services:
  title: The Service Layer
  declarativeTransactions:
    title: Declarative Transactions
    transactionsMultiDataSource: Transactions and Multi-DataSources
    transactionsRollbackAndTheSession: Transactions Rollback and the Session
  scopedServices: Scoped Services
  dependencyInjectionServices: Dependency Injection and Services
staticTypeCheckingAndCompilation:
  title: Static Type Checking And Compilation
  grailsCompileStatic: The GrailsCompileStatic Annotation
  grailsTypeChecked: The GrailsTypeChecked Annotation
testing:
  title: Testing
  generatingTests: Generating Tests
  runningTests:
    title: Running Tests
    withGrailsCli: With Grails CLI
    withGradle: With Gradle
  unitTesting:
    title: Unit Testing
    installation: Installation
    upgradingMixin: Upgrading From The Mixin Framework
    unitTestingControllers: Unit Testing Controllers
    unitTestingDomainClasses: Unit Testing Domain Classes
    unitTestingServices: Unit Testing Services
    unitTestingTagLibraries: Unit Testing Tag Libraries
    unitTestingInterceptors: Unit Testing Interceptors
    unitTestingUrlMappings: Unit Testing Url Mappings
    annotations: Annotations
    usefulProperties: Useful Properties
  integrationTesting: Integration Testing
  functionalTesting: Functional Testing
  testPhases: Custom Test Phases
  testingMongodb: Testing GORM for MongoDB
bestPractices:
  title: Building a Successful Application
  codeAnalysisGroovy: Code Analysis and Styling for Groovy
i18n:
  title: Internationalization
  understandingMessageBundles: Understanding Message Bundles
  changingLocales: Changing Locales
  readingMessages: Reading Messages
  scaffoldingAndI18n: Scaffolding and i18n
security:
  title: Security
  securingAgainstAttacks: Securing Against Attacks
  xssPrevention: Cross Site Scripting (XSS) Prevention
  codecs: Encoding and Decoding Objects
  authentication: Authentication
  securityPlugins:
    title: Security Plugins
    springSecurity:
      title: Spring Security
      springSecurityCore: Core Plugin
      springSecurityAcl: ACL Plugin
      springSecurityCas: CAS Plugin
      springSecurityLdap: LDAP Plugin
      springSecurityOauth2: OAuth2 Plugin
      springSecurityRest: REST Plugin
      springSecurityUi: UI Plugin
mail:
  title: Mail
  mailConfiguration: Configuration
  mailSendingEmails: Sending Emails
  mailMessageContent: Message Content
  mailAttachments: Attachments
  mailTesting: Testing
backgroundJobs:
  title: Background Jobs
  backgroundJobsBasic: Basic Scheduling
  backgroundJobsAdvanced:
    title: Advanced Scheduling
    quartzInstallation: Installation
    quartzScheduling: Writing Jobs
    quartzTriggers: Triggers
    quartzJobProperties: Job Properties
    quartzDynamicScheduling: Dynamic Job Scheduling
    quartzJobManagerService: Managing Jobs at Runtime
    quartzLongRunningJobs: Long-Running Jobs
    quartzConfiguration: Configuration
    quartzClustering: Clustering
    quartzUsefulLinks: Useful Links
redis:
  title: Redis
  redisInstallation: Installation and Configuration
  redisUsage: Using the redisService
  redisMemoization: Memoization
  redisMemoizationAnnotations: Memoization Annotations
  redisMultipleServers: Multiple Redis Servers
  redisUsefulLinks: Useful Links
plugins:
  title: Plugins
  creatingAndInstallingPlugins: Creating and Installing Plugins
  repositories: Plugin Repositories
  providingBasicArtefacts: Providing Basic Artefacts
  evaluatingConventions: Evaluating Conventions
  hookingIntoRuntimeConfiguration: Hooking into Runtime Configuration
  addingMethodsAtCompileTime: Adding Methods at Compile Time
  addingDynamicMethodsAtRuntime: Adding Dynamic Methods at Runtime
  participatingInAutoReloadEvents: Participating in Auto Reload Events
  understandingPluginLoadOrder: Understanding Plugin Load Order
  artefactApi:
    title: The Artefact API
    queryingArtefacts: Asking About Available Artefacts
    customArtefacts: Adding Your Own Artefact Types
spring:
  title: Grails and Spring
  springdslAdditional: Configuring Additional Beans
  springdsl: Runtime Spring with the Beans DSL
  theBeanBuilderDSLExplained: The BeanBuilder DSL Explained
  propertyPlaceholderConfiguration: Property Placeholder Configuration
  propertyOverrideConfiguration: Property Override Configuration
  actuators: Spring Boot Actuators
scaffolding: Scaffolding
cache:
  title: Grails Cache
  cacheUsage:
    title: Usage
    cacheConfiguration: Configuration
    cacheAnnotations:
      title: Cache Annotations
      cacheUnitTests: Unit Testing
    cacheManager: The CacheManager
  cacheTags: Caching Tags
  grailsCacheAdminService:
    title: The Cache Admin Service
    clearingCaches: Clearing Caches
  cacheImplementation: Implementation Details
deployment:
  title: Deployment
  deploymentStandalone: Standalone
  deploymentContainer: Container Deployment (e.g. Tomcat)
  deploymentTasks: Deployment Configuration Tasks
  deploymentAot: Ahead-of-Time Processing
  deploymentAotCache: Ahead-of-Time Caching
contributing:
  title: Contributing to Grails
