/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */

plugins {
    id 'project-report'
    id 'org.apache.grails.buildsrc.properties'
    id 'org.apache.grails.buildsrc.dependency-validator'
    id 'org.apache.grails.gradle.grails-plugin'
    id 'org.apache.grails.buildsrc.compile'
    id 'org.apache.grails.buildsrc.publish'
    id 'org.apache.grails.buildsrc.sbom'
    id 'org.apache.grails.buildsrc.vulnerability-scan'
    id 'org.apache.grails.gradle.grails-code-style'
    id 'org.apache.grails.gradle.grails-jacoco'
}

version = projectVersion
group = 'org.apache.grails'

ext {
    pomTitle = 'Grails Cache Plugin'
    pomDescription = 'Provides AST transformations for caching method calls'
}

dependencies {
    implementation platform(project(':grails-bom'))
    astCompileOnly platform(project(':grails-bom'))

    astCompileOnly 'org.slf4j:slf4j-nop' // Prevents warning about missing slf4j implementation during compilation

    api project(':grails-core')
    api project(':grails-web-boot')
    api project(':grails-services')

    api project(':grails-gsp')
    api "org.codehaus.gpars:gpars:$gparsVersion"
    api 'com.github.ben-manes.caffeine:caffeine'

    compileOnly project(':grails-domain-class')
    compileOnly 'org.slf4j:slf4j-nop' // Prevents warning about missing slf4j implementation during compilation

    console project(':grails-console')

    testImplementation project(':grails-testing-support-datamapping')
    testImplementation project(':grails-testing-support-web')
    testImplementation 'org.spockframework:spock-core'

    testCompileOnly 'org.slf4j:slf4j-nop' // Prevents warning about missing slf4j implementation during compilation

    testRuntimeOnly 'net.bytebuddy:byte-buddy' // Required by Spock's mocking support
}

apply {
    from rootProject.layout.projectDirectory.file('gradle/docs-config.gradle')
    from rootProject.layout.projectDirectory.file('gradle/test-config.gradle')
    from rootProject.layout.projectDirectory.file('gradle/grails-extension-gradle-config.gradle')
}
