/*
 *  Licensed to the Apache Software Foundation (ASF) under one or more
 *  contributor license agreements.  See the NOTICE file distributed with
 *  this work for additional information regarding copyright ownership.
 *  The ASF licenses this file to You under the Apache License, Version 2.0
 *  (the "License"); you may not use this file except in compliance with
 *  the License.  You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

// Vendored Spring Framework ORM Hibernate 7 integration classes.
// These classes are moved here to align with the structure of Hibernate 5.

plugins {
    id 'groovy'
    id 'java-library'
    id 'org.apache.grails.buildsrc.properties'
    id 'org.apache.grails.buildsrc.dependency-validator'
    id 'org.apache.grails.buildsrc.compile'
    id 'org.apache.grails.buildsrc.publish'
    id 'org.apache.grails.buildsrc.sbom'
    id 'org.apache.grails.gradle.grails-code-style'
}

version = projectVersion
group = 'org.apache.grails.data'

ext {
    pomTitle = 'Grails GORM ORM Hibernate 7 Support'
    pomDescription = 'Vendored Spring Framework ORM Hibernate 7 integration classes for Grails GORM'
}

dependencies {
    implementation platform(project(':grails-hibernate7-bom'))

    api 'org.slf4j:slf4j-api'
    api 'org.apache.groovy:groovy'
    api 'org.springframework:spring-orm'
    api 'org.springframework:spring-web'
    api 'org.springframework:spring-tx'
    api 'org.springframework:spring-beans'
    api 'org.springframework:spring-context'
    compileOnly 'jakarta.servlet:jakarta.servlet-api'
    api 'org.hibernate.orm:hibernate-core', {
        exclude group: 'commons-logging', module: 'commons-logging'
        exclude group: 'org.slf4j', module: 'slf4j-api'
    }
}

// Javadoc references Spring Framework internals not on our classpath - suppress errors for vendored code
tasks.withType(Javadoc).configureEach {
    options.addStringOption('Xdoclint:none', '-quiet')
    failOnError = false
}
