/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */
plugins {
    id 'org.apache.grails.buildsrc.properties'
    id 'org.apache.grails.buildsrc.dependency-validator'
    id 'org.apache.grails.buildsrc.compile'
}

version = '0.1'
group = 'undertowapp'

apply plugin: 'org.apache.grails.gradle.grails-web'
apply plugin: 'org.apache.grails.gradle.grails-gsp'
apply plugin: 'cloud.wondrify.asset-pipeline'

dependencies {
    implementation platform(project(':grails-bom'))

    implementation 'org.springframework.boot:spring-boot-starter-logging'
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.apache.grails:grails-core'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.apache.grails:grails-undertow'
    implementation 'org.apache.grails:grails-web-boot'
    if (System.getenv('SITEMESH2_TESTING_ENABLED') == 'true') {
        implementation 'org.apache.grails:grails-layout'
    } else {
        implementation 'org.apache.grails:grails-sitemesh3'
    }
    implementation 'org.apache.grails:grails-logging'
    implementation 'org.apache.grails:grails-rest-transforms'
    implementation 'org.apache.grails:grails-databinding'
    implementation 'org.apache.grails:grails-services'
    implementation 'org.apache.grails:grails-url-mappings'
    implementation 'org.apache.grails:grails-interceptors'
    implementation 'org.apache.grails:grails-gsp'

    testAndDevelopmentOnly platform(project(':grails-bom'))
    testAndDevelopmentOnly 'org.webjars.npm:bootstrap'
    testAndDevelopmentOnly 'org.webjars.npm:jquery'

    runtimeOnly 'cloud.wondrify:asset-pipeline-grails'

    testCompileOnly 'org.slf4j:slf4j-nop' // Prevents warning about missing slf4j implementation during compilation

    integrationTestImplementation testFixtures('org.apache.grails:grails-geb')
    integrationTestImplementation 'org.apache.grails:grails-testing-support-http-client'
}

apply {
    from rootProject.layout.projectDirectory.file('gradle/functional-test-config.gradle')
    from rootProject.layout.projectDirectory.file('gradle/test-webjar-asset-config.gradle')
    from rootProject.layout.projectDirectory.file('gradle/grails-extension-gradle-config.gradle')
}
